# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html

before_script:
#  - docker info
#  - docker build --tag=gta-devel --build-arg http_proxy=http://proxy-us.intel.com:911 --build-arg https_proxy=http://proxy-us.intel.com:911 cicd
  - git config --global http.proxy http://proxy-us.intel.com:911
  - git config --global https.proxy http://proxy-us.intel.com:911
  - git config --global url."ssh://git@gitlab.devtools.intel.com:29418".insteadOf https://gitlab.devtools.intel.com

variables:
  http_proxy: http://proxy-us.intel.com:911
  https_proxy: http://proxy-us.intel.com:911
  no_proxy: ".intel.com"

stages:
  - build
  - test

build:gta:
  stage: build
  image: gta-devel
  tags:
    - gta
  script:
    - go build ./...

test:
  stage: test
  image: gta-devel
  tags:
    - gta
  dependencies:
    - build:gta
  script:
    - go test ./... -coverpkg=./... -coverprofile cover.out
    - go tool cover -func cover.out
    - go tool cover -html=cover.out -o cover.html
  artifacts:
    paths:
      - "cover.html"