# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html

image: gta-devel

before_script:
  - docker info
  - git config --global http.proxy http://proxy-us.intel.com:911
  - git config --global https.proxy http://proxy-us.intel.com:911
  - git config --global url."ssh://git@gitlab.devtools.intel.com:29418".insteadOf https://gitlab.devtools.intel.com

variables:
  http_proxy: http://proxy-us.intel.com:911
  https_proxy: http://proxy-us.intel.com:911
  no_proxy: ".intel.com"

stages:
  - build
  - test

build:docker_image:
  stage: build
  script:
    - docker image inspect gta-devel || if [ $? -eq 0 ]; then echo "The gta-devel image is present and will not be created"; else docker build --tag=gta-devel --build-arg http_proxy=http://proxy-us.intel.com:911 --build-arg https_proxy=http://proxy-us.intel.com:911 cicd; fi

build:gta:
  stage: build
  tags:
    - gta
  dependencies:
    - build:docker_image
  script:
    - go build ./...

test:
  stage: test
  tags:
    - go
  dependencies:
    - build:gta
  script:
    - go test ./... -coverpkg=./... -coverprofile cover.out
    - go tool cover -func cover.out
    - go tool cover -html=cover.out -o cover.html
  artifacts:
    paths:
      - "cover.html"