# Requires:
#  - 'gta-devel' docker image installed on local host (see commnents in /cicd/Dockerfile)
#  - gitlab-runner installed
# Local run: gitlab-runner exec docker -docker-pull-policy never build:gta

before_script:
  - git config --global http.proxy http://proxy-us.intel.com:911
  - git config --global https.proxy http://proxy-us.intel.com:911
  - git config --global url."ssh://git@gitlab.devtools.intel.com:29418".insteadOf https://gitlab.devtools.intel.com
  - export http_proxy=http://proxy-us.intel.com:911
  - export https_proxy=http://proxy-us.intel.com:911
  - export no_proxy=127.0.0.1,localhost
  - cd $CI_PROJECT_DIR

stages:
  - build
  - test

build:gta:
  stage: build
  image: gta-devel
  tags:
    - gta
  script:
    - make installer
  artifacts:
    paths:
      - "out/tagent-*.bin"
      - "out/tagent"
    expire_in: 1 week

test:
  stage: test
  image: gta-devel
  tags:
    - gta
  dependencies:
    - build:gta
  script:
    - go test ./... -coverpkg=./... -coverprofile cover.out
    - go tool cover -func cover.out
    - go tool cover -html=cover.out -o cover.html
  artifacts:
    paths:
      - "cover.html"